import { createContext, useContext, useState, ReactNode } from "react";

type Language = "en" | "es" | "fr" | "hi" | "gu";

type Translations = {
    [key in Language]: {
        [key: string]: string;
    };
};

const translations: Translations = {
    en: {
        "nav.intro": "Intro",
        "nav.diagram": "Diagram",
        "nav.llms": "LLMs",
        "nav.agents": "Agents",
        "nav.workflows": "Workflows",
        "nav.architecture": "Architecture",
        "hero.title": "The Age of Autonomous AI",
        "hero.subtitle": "From simple chatbots to intelligent agents that can plan, reason, and execute tasks.",
        "hero.cta": "Start Learning",
        "section.talking_vs_doing": "Talking vs. Doing",
        "section.talking_vs_doing.subtitle": "How AI is moving from just chatting to actually getting work done.",
        "section.intro.big_shift.title": "The Big Shift",
        "section.intro.big_shift.text": "AI is changing. It used to just answer questions. Now, it can act. We are moving from \"Chatbots\" that talk, to \"Agents\" that do. This means AI can now plan, learn, and help you finish tasks, not just write about them.",
        "section.intro.analogy.text1": "Think of it this way: Old AI was like a smart encyclopedia. It knew a lot but couldn't do anything. New AI (Agentic AI) is like a smart intern. It knows things AND can do work for you.",
        "section.intro.analogy.text2": "This is huge for businesses. Instead of just getting answers, you can now automate entire jobs. It's about getting results, not just text.",
        "section.intro.future.title": "Future Outlook",
        "section.intro.future.text": "By 2028, experts say 15% of work decisions will be made by these autonomous agents. It's the next big step in automation.",
        "section.diagram": "How Agents Think",
        "section.diagram.subtitle": "The simple loop that lets AI solve problems on its own.",
        "section.llms": "The Brain: LLMs",
        "section.llms.subtitle": "Understanding the core technology behind the magic.",
        "section.llms.student.title": "The Smart Student",
        "section.llms.student.text": "A Large Language Model (LLM) is like a student who has read every book in the library. It knows a lot about everything—history, science, coding. It uses this knowledge to predict what to say next.",
        "section.llms.pros_cons.title": "Pros & Cons",
        "section.llms.pros_cons.fast.title": "Super Fast",
        "section.llms.pros_cons.fast.desc": "Great at writing, summarizing, and answering questions instantly.",
        "section.llms.pros_cons.cant_act.title": "Can't Act",
        "section.llms.pros_cons.cant_act.desc": "It's trapped in a box. It can write an email, but it can't send it.",
        "section.llms.pros_cons.wrong.title": "Can Be Wrong",
        "section.llms.pros_cons.wrong.desc": "Sometimes it makes things up (hallucinations) if it doesn't know the answer.",
        "section.llms.pros_cons.memory.title": "No Memory",
        "section.llms.pros_cons.memory.desc": "It forgets everything once the chat ends. It doesn't learn from mistakes.",
        "section.llms.smarter.title": "Making It Smarter",
        "section.llms.smarter.finetuning.title": "Specialized Training",
        "section.llms.smarter.finetuning.desc": "Like sending a doctor to medical school. We teach the AI specific things so it becomes an expert in one field.",
        "section.llms.smarter.rag.title": "Open Book Test",
        "section.llms.smarter.rag.desc": "Instead of memorizing everything, we let the AI look up facts in a trusted book or database. This stops it from making things up.",
        "section.agents": "Enter: AI Agents",
        "section.agents.subtitle": "Giving the brain hands and feet.",
        "section.agents.worker.title": "The Digital Worker",
        "section.agents.worker.text": "An AI Agent is an LLM with tools. It can use a web browser, send emails, or run code. It doesn't just talk; it does. It has a goal, makes a plan, and executes it.",
        "section.agents.worker.note": "LLM = Thinker. Agent = Doer.",
        "section.agents.diff.title": "Key Differences",
        "section.agents.diff.llm.title": "LLM (Static)",
        "section.agents.diff.llm.desc": "Waiting for you to ask a question. Forgets you immediately after.",
        "section.agents.diff.agent.title": "Agent (Active)",
        "section.agents.diff.agent.desc": "Works towards a goal. Remembers what it did. Learns from mistakes.",
        "section.agents.comparison.title": "Quick Comparison",
        "section.architecture": "What's Inside an Agent?",
        "section.architecture.subtitle": "The parts that make it work.",
        "section.architecture.text": "An agent isn't magic. It's a system. It needs a Brain (LLM), Memory (to remember context), and Tools (to interact with the world).",
        "section.architecture.react.title": "Thinking Step-by-Step (ReAct)",
        "section.architecture.react.subtitle": "Reason & Act",
        "section.architecture.react.text": "This is how agents solve hard problems. They don't guess. They: 1. Think about what to do. 2. Act (use a tool). 3. Observe the result. 4. Repeat until finished.",
        "section.workflows": "Agent Teams",
        "section.workflows.subtitle": "When one agent isn't enough.",
        "section.workflows.title": "Workflows",
        "section.workflows.text": "Sometimes a job is too big for one agent. So we connect them. One agent might be the \"Researcher\", another the \"Writer\", and another the \"Editor\". They pass work to each other like a real team.",
        "section.workflows.advanced.title": "Advanced Features",
        "section.workflows.advanced.teamwork.title": "Teamwork",
        "section.workflows.advanced.teamwork.desc": "Multiple agents working together on complex projects.",
        "section.workflows.advanced.reflection.title": "Self-Reflection",
        "section.workflows.advanced.reflection.desc": "Agents checking their own work to make sure it's good.",
        "section.workflows.advanced.human.title": "Human Help",
        "section.workflows.advanced.human.desc": "Asking a human for approval before doing something important.",
        "section.workflows.advanced.adapt.title": "Adaptability",
        "section.workflows.advanced.adapt.desc": "Changing the plan if something goes wrong.",
        "section.workflows.future.title": "The Future of Work",
        "section.workflows.future.text": "This is the future. Digital workers handling the boring stuff, so you can focus on the big ideas.",
        "listen": "Listen",
    },
    es: {
        "nav.intro": "Intro",
        "nav.diagram": "Diagrama",
        "nav.llms": "LLMs",
        "nav.agents": "Agentes",
        "nav.workflows": "Flujos",
        "nav.architecture": "Arquitectura",
        "hero.title": "La Era de la IA Autónoma",
        "hero.subtitle": "De simples chatbots a agentes inteligentes que pueden planificar, razonar y ejecutar tareas.",
        "hero.cta": "Comenzar a Aprender",
        "section.talking_vs_doing": "Hablar vs. Hacer",
        "section.talking_vs_doing.subtitle": "Cómo la IA está pasando de solo chatear a realizar trabajo real.",
        "section.intro.big_shift.title": "El Gran Cambio",
        "section.intro.big_shift.text": "La IA está cambiando. Antes solo respondía preguntas. Ahora, puede actuar. Estamos pasando de \"Chatbots\" que hablan, a \"Agentes\" que hacen. Esto significa que la IA ahora puede planificar, aprender y ayudarte a terminar tareas, no solo escribir sobre ellas.",
        "section.intro.analogy.text1": "Piénsalo de esta manera: La vieja IA era como una enciclopedia inteligente. Sabía mucho pero no podía hacer nada. La nueva IA (IA Agéntica) es como un pasante inteligente. Sabe cosas Y puede hacer trabajo por ti.",
        "section.intro.analogy.text2": "Esto es enorme para las empresas. En lugar de solo obtener respuestas, ahora puedes automatizar trabajos completos. Se trata de obtener resultados, no solo texto.",
        "section.intro.future.title": "Perspectiva Futura",
        "section.intro.future.text": "Para 2028, los expertos dicen que el 15% de las decisiones laborales serán tomadas por estos agentes autónomos. Es el siguiente gran paso en la automatización.",
        "section.diagram": "Cómo Piensan los Agentes",
        "section.diagram.subtitle": "El bucle simple que permite a la IA resolver problemas por sí misma.",
        "section.llms": "El Cerebro: LLMs",
        "section.llms.subtitle": "Entendiendo la tecnología central detrás de la magia.",
        "section.llms.student.title": "El Estudiante Inteligente",
        "section.llms.student.text": "Un Modelo de Lenguaje Grande (LLM) es como un estudiante que ha leído todos los libros de la biblioteca. Sabe mucho sobre todo: historia, ciencia, programación. Usa este conocimiento para predecir qué decir a continuación.",
        "section.llms.pros_cons.title": "Pros y Contras",
        "section.llms.pros_cons.fast.title": "Súper Rápido",
        "section.llms.pros_cons.fast.desc": "Genial para escribir, resumir y responder preguntas al instante.",
        "section.llms.pros_cons.cant_act.title": "No Puede Actuar",
        "section.llms.pros_cons.cant_act.desc": "Está atrapado en una caja. Puede escribir un correo electrónico, pero no puede enviarlo.",
        "section.llms.pros_cons.wrong.title": "Puede Equivocarse",
        "section.llms.pros_cons.wrong.desc": "A veces inventa cosas (alucinaciones) si no sabe la respuesta.",
        "section.llms.pros_cons.memory.title": "Sin Memoria",
        "section.llms.pros_cons.memory.desc": "Olvida todo una vez que termina el chat. No aprende de los errores.",
        "section.llms.smarter.title": "Haciéndolo Más Inteligente",
        "section.llms.smarter.finetuning.title": "Entrenamiento Especializado",
        "section.llms.smarter.finetuning.desc": "Como enviar a un médico a la escuela de medicina. Enseñamos a la IA cosas específicas para que se convierta en experta en un campo.",
        "section.llms.smarter.rag.title": "Examen a Libro Abierto",
        "section.llms.smarter.rag.desc": "En lugar de memorizar todo, dejamos que la IA busque hechos en un libro o base de datos confiable. Esto evita que invente cosas.",
        "section.agents": "Entran: Agentes de IA",
        "section.agents.subtitle": "Dando manos y pies al cerebro.",
        "section.agents.worker.title": "El Trabajador Digital",
        "section.agents.worker.text": "Un Agente de IA es un LLM con herramientas. Puede usar un navegador web, enviar correos electrónicos o ejecutar código. No solo habla; hace. Tiene un objetivo, hace un plan y lo ejecuta.",
        "section.agents.worker.note": "LLM = Pensador. Agente = Hacedor.",
        "section.agents.diff.title": "Diferencias Clave",
        "section.agents.diff.llm.title": "LLM (Estático)",
        "section.agents.diff.llm.desc": "Esperando a que hagas una pregunta. Te olvida inmediatamente después.",
        "section.agents.diff.agent.title": "Agente (Activo)",
        "section.agents.diff.agent.desc": "Trabaja hacia un objetivo. Recuerda lo que hizo. Aprende de los errores.",
        "section.agents.comparison.title": "Comparación Rápida",
        "section.architecture": "¿Qué hay dentro de un Agente?",
        "section.architecture.subtitle": "Las partes que lo hacen funcionar.",
        "section.architecture.text": "Un agente no es magia. Es un sistema. Necesita un Cerebro (LLM), Memoria (para recordar el contexto) y Herramientas (para interactuar con el mundo).",
        "section.architecture.react.title": "Pensando Paso a Paso (ReAct)",
        "section.architecture.react.subtitle": "Razonar y Actuar",
        "section.architecture.react.text": "Así es como los agentes resuelven problemas difíciles. No adivinan. Ellos: 1. Piensan qué hacer. 2. Actúan (usan una herramienta). 3. Observan el resultado. 4. Repiten hasta terminar.",
        "section.workflows": "Equipos de Agentes",
        "section.workflows.subtitle": "Cuando un agente no es suficiente.",
        "section.workflows.title": "Flujos de Trabajo",
        "section.workflows.text": "A veces un trabajo es demasiado grande para un solo agente. Así que los conectamos. Un agente podría ser el \"Investigador\", otro el \"Escritor\" y otro el \"Editor\". Se pasan el trabajo entre ellos como un equipo real.",
        "section.workflows.advanced.title": "Características Avanzadas",
        "section.workflows.advanced.teamwork.title": "Trabajo en Equipo",
        "section.workflows.advanced.teamwork.desc": "Múltiples agentes trabajando juntos en proyectos complejos.",
        "section.workflows.advanced.reflection.title": "Auto-Reflexión",
        "section.workflows.advanced.reflection.desc": "Agentes revisando su propio trabajo para asegurarse de que sea bueno.",
        "section.workflows.advanced.human.title": "Ayuda Humana",
        "section.workflows.advanced.human.desc": "Pedir aprobación a un humano antes de hacer algo importante.",
        "section.workflows.advanced.adapt.title": "Adaptabilidad",
        "section.workflows.advanced.adapt.desc": "Cambiar el plan si algo sale mal.",
        "section.workflows.future.title": "El Futuro del Trabajo",
        "section.workflows.future.text": "Este es el futuro. Trabajadores digitales manejando las cosas aburridas, para que puedas concentrarte en las grandes ideas.",
        "listen": "Escuchar",
    },
    fr: {
        "nav.intro": "Intro",
        "nav.diagram": "Diagramme",
        "nav.llms": "LLMs",
        "nav.agents": "Agents",
        "nav.workflows": "Flux",
        "nav.architecture": "Architecture",
        "hero.title": "L'Ère de l'IA Autonome",
        "hero.subtitle": "Des chatbots simples aux agents intelligents capables de planifier, raisonner et exécuter des tâches.",
        "hero.cta": "Commencer à Apprendre",
        "section.talking_vs_doing": "Parler vs. Faire",
        "section.talking_vs_doing.subtitle": "Comment l'IA passe du simple chat à l'exécution réelle du travail.",
        "section.intro.big_shift.title": "Le Grand Changement",
        "section.intro.big_shift.text": "L'IA change. Elle ne faisait que répondre aux questions. Maintenant, elle peut agir. Nous passons des \"Chatbots\" qui parlent aux \"Agents\" qui font. Cela signifie que l'IA peut désormais planifier, apprendre et vous aider à terminer des tâches, pas seulement écrire à leur sujet.",
        "section.intro.analogy.text1": "Pensez-y de cette façon : L'ancienne IA était comme une encyclopédie intelligente. Elle savait beaucoup de choses mais ne pouvait rien faire. La nouvelle IA (IA Agentique) est comme un stagiaire intelligent. Elle sait des choses ET peut travailler pour vous.",
        "section.intro.analogy.text2": "C'est énorme pour les entreprises. Au lieu de simplement obtenir des réponses, vous pouvez désormais automatiser des emplois entiers. Il s'agit d'obtenir des résultats, pas seulement du texte.",
        "section.intro.future.title": "Perspectives d'Avenir",
        "section.intro.future.text": "D'ici 2028, les experts disent que 15 % des décisions de travail seront prises par ces agents autonomes. C'est la prochaine grande étape de l'automatisation.",
        "section.diagram": "Comment Pensent les Agents",
        "section.diagram.subtitle": "La boucle simple qui permet à l'IA de résoudre des problèmes par elle-même.",
        "section.llms": "Le Cerveau : LLMs",
        "section.llms.subtitle": "Comprendre la technologie de base derrière la magie.",
        "section.llms.student.title": "L'Étudiant Intelligent",
        "section.llms.student.text": "Un Grand Modèle de Langage (LLM) est comme un étudiant qui a lu tous les livres de la bibliothèque. Il sait beaucoup de choses sur tout : histoire, science, code. Il utilise ces connaissances pour prédire ce qu'il faut dire ensuite.",
        "section.llms.pros_cons.title": "Avantages et Inconvénients",
        "section.llms.pros_cons.fast.title": "Super Rapide",
        "section.llms.pros_cons.fast.desc": "Idéal pour écrire, résumer et répondre aux questions instantanément.",
        "section.llms.pros_cons.cant_act.title": "Ne Peut Pas Agir",
        "section.llms.pros_cons.cant_act.desc": "Il est piégé dans une boîte. Il peut écrire un e-mail, mais il ne peut pas l'envoyer.",
        "section.llms.pros_cons.wrong.title": "Peut Se Tromper",
        "section.llms.pros_cons.wrong.desc": "Parfois, il invente des choses (hallucinations) s'il ne connaît pas la réponse.",
        "section.llms.pros_cons.memory.title": "Pas de Mémoire",
        "section.llms.pros_cons.memory.desc": "Il oublie tout une fois le chat terminé. Il n'apprend pas de ses erreurs.",
        "section.llms.smarter.title": "Le Rendre Plus Intelligent",
        "section.llms.smarter.finetuning.title": "Formation Spécialisée",
        "section.llms.smarter.finetuning.desc": "Comme envoyer un médecin à l'école de médecine. Nous enseignons à l'IA des choses spécifiques pour qu'elle devienne experte dans un domaine.",
        "section.llms.smarter.rag.title": "Examen à Livre Ouvert",
        "section.llms.smarter.rag.desc": "Au lieu de tout mémoriser, nous laissons l'IA rechercher des faits dans un livre ou une base de données de confiance. Cela l'empêche d'inventer des choses.",
        "section.agents": "Entrez : Agents IA",
        "section.agents.subtitle": "Donner des mains et des pieds au cerveau.",
        "section.agents.worker.title": "Le Travailleur Numérique",
        "section.agents.worker.text": "Un Agent IA est un LLM avec des outils. Il peut utiliser un navigateur web, envoyer des e-mails ou exécuter du code. Il ne fait pas que parler ; il fait. Il a un objectif, fait un plan et l'exécute.",
        "section.agents.worker.note": "LLM = Penseur. Agent = Faiseur.",
        "section.agents.diff.title": "Différences Clés",
        "section.agents.diff.llm.title": "LLM (Statique)",
        "section.agents.diff.llm.desc": "Attend que vous posiez une question. Vous oublie immédiatement après.",
        "section.agents.diff.agent.title": "Agent (Actif)",
        "section.agents.diff.agent.desc": "Travaille vers un objectif. Se souvient de ce qu'il a fait. Apprend de ses erreurs.",
        "section.agents.comparison.title": "Comparaison Rapide",
        "section.architecture": "Qu'y a-t-il dans un Agent ?",
        "section.architecture.subtitle": "Les parties qui le font fonctionner.",
        "section.architecture.text": "Un agent n'est pas magique. C'est un système. Il a besoin d'un Cerveau (LLM), d'une Mémoire (pour se souvenir du contexte) et d'Outils (pour interagir avec le monde).",
        "section.architecture.react.title": "Penser Étape par Étape (ReAct)",
        "section.architecture.react.subtitle": "Raisonner et Agir",
        "section.architecture.react.text": "C'est ainsi que les agents résolvent des problèmes difficiles. Ils ne devinent pas. Ils : 1. Pensent à ce qu'il faut faire. 2. Agissent (utilisent un outil). 3. Observent le résultat. 4. Répètent jusqu'à ce que ce soit fini.",
        "section.workflows": "Équipes d'Agents",
        "section.workflows.subtitle": "Quand un agent ne suffit pas.",
        "section.workflows.title": "Flux de Travail",
        "section.workflows.text": "Parfois, un travail est trop gros pour un seul agent. Alors nous les connectons. Un agent pourrait être le \"Chercheur\", un autre le \"Rédacteur\", et un autre l'\"Éditeur\". Ils se passent le travail comme une vraie équipe.",
        "section.workflows.advanced.title": "Fonctionnalités Avancées",
        "section.workflows.advanced.teamwork.title": "Travail d'Équipe",
        "section.workflows.advanced.teamwork.desc": "Plusieurs agents travaillant ensemble sur des projets complexes.",
        "section.workflows.advanced.reflection.title": "Auto-Réflexion",
        "section.workflows.advanced.reflection.desc": "Agents vérifiant leur propre travail pour s'assurer qu'il est bon.",
        "section.workflows.advanced.human.title": "Aide Humaine",
        "section.workflows.advanced.human.desc": "Demander l'approbation d'un humain avant de faire quelque chose d'important.",
        "section.workflows.advanced.adapt.title": "Adaptabilité",
        "section.workflows.advanced.adapt.desc": "Changer le plan si quelque chose ne va pas.",
        "section.workflows.future.title": "L'Avenir du Travail",
        "section.workflows.future.text": "C'est l'avenir. Des travailleurs numériques gérant les choses ennuyeuses, pour que vous puissiez vous concentrer sur les grandes idées.",
        "listen": "Écouter",
    },
    hi: {
        "nav.intro": "परिचय",
        "nav.diagram": "आरेख",
        "nav.llms": "LLMs",
        "nav.agents": "एजेंट्स",
        "nav.workflows": "कार्यप्रवाह",
        "nav.architecture": "वास्तुकला",
        "hero.title": "स्वायत्त एआई का युग",
        "hero.subtitle": "साधारण चैटबॉट से लेकर बुद्धिमान एजेंटों तक जो योजना बना सकते हैं, तर्क कर सकते हैं और कार्यों को निष्पादित कर सकते हैं।",
        "hero.cta": "सीखना शुरू करें",
        "section.talking_vs_doing": "बात करना बनाम काम करना",
        "section.talking_vs_doing.subtitle": "एआई कैसे सिर्फ चैटिंग से वास्तव में काम करने की ओर बढ़ रहा है।",
        "section.intro.big_shift.title": "बड़ा बदलाव",
        "section.intro.big_shift.text": "एआई बदल रहा है। यह पहले सिर्फ सवालों के जवाब देता था। अब, यह कार्य कर सकता है। हम \"चैटबॉट्स\" से जो बात करते हैं, \"एजेंट्स\" की ओर बढ़ रहे हैं जो काम करते हैं। इसका मतलब है कि एआई अब योजना बना सकता है, सीख सकता है, और आपके कार्यों को पूरा करने में मदद कर सकता है, न कि केवल उनके बारे में लिख सकता है।",
        "section.intro.analogy.text1": "इसे इस तरह सोचें: पुराना एआई एक स्मार्ट विश्वकोश की तरह था। यह बहुत कुछ जानता था लेकिन कुछ कर नहीं सकता था। नया एआई (एजेंटिक एआई) एक स्मार्ट इंटर्न की तरह है। यह चीजें जानता है और आपके लिए काम भी कर सकता है।",
        "section.intro.analogy.text2": "यह व्यवसायों के लिए बहुत बड़ा है। केवल उत्तर प्राप्त करने के बजाय, अब आप पूरी नौकरियों को स्वचालित कर सकते हैं। यह परिणाम प्राप्त करने के बारे में है, न कि केवल पाठ।",
        "section.intro.future.title": "भविष्य का दृष्टिकोण",
        "section.intro.future.text": "2028 तक, विशेषज्ञों का कहना है कि 15% कार्य निर्णय इन स्वायत्त एजेंटों द्वारा लिए जाएंगे। यह स्वचालन में अगला बड़ा कदम है।",
        "section.diagram": "एजेंट कैसे सोचते हैं",
        "section.diagram.subtitle": "वह सरल लूप जो एआई को अपने आप समस्याओं को हल करने देता है।",
        "section.llms": "मस्तिष्क: LLMs",
        "section.llms.subtitle": "जादू के पीछे की मुख्य तकनीक को समझना।",
        "section.llms.student.title": "स्मार्ट छात्र",
        "section.llms.student.text": "एक बड़ा भाषा मॉडल (LLM) एक छात्र की तरह है जिसने पुस्तकालय में हर किताब पढ़ी है। यह सब कुछ के बारे में बहुत कुछ जानता है—इतिहास, विज्ञान, कोडिंग। यह इस ज्ञान का उपयोग यह अनुमान लगाने के लिए करता है कि आगे क्या कहना है।",
        "section.llms.pros_cons.title": "फायदे और नुकसान",
        "section.llms.pros_cons.fast.title": "सुपर फास्ट",
        "section.llms.pros_cons.fast.desc": "लिखने, सारांशित करने और तुरंत सवालों के जवाब देने में महान।",
        "section.llms.pros_cons.cant_act.title": "कार्य नहीं कर सकता",
        "section.llms.pros_cons.cant_act.desc": "यह एक बॉक्स में फंसा हुआ है। यह एक ईमेल लिख सकता है, लेकिन इसे भेज नहीं सकता।",
        "section.llms.pros_cons.wrong.title": "गलत हो सकता है",
        "section.llms.pros_cons.wrong.desc": "कभी-कभी यह चीजें बना देता है (भ्रम) यदि इसे उत्तर नहीं पता है।",
        "section.llms.pros_cons.memory.title": "कोई स्मृति नहीं",
        "section.llms.pros_cons.memory.desc": "चैट समाप्त होने के बाद यह सब कुछ भूल जाता है। यह गलतियों से नहीं सीखता है।",
        "section.llms.smarter.title": "इसे और होशियार बनाना",
        "section.llms.smarter.finetuning.title": "विशेष प्रशिक्षण",
        "section.llms.smarter.finetuning.desc": "जैसे डॉक्टर को मेडिकल स्कूल भेजना। हम एआई को विशिष्ट चीजें सिखाते हैं ताकि वह एक क्षेत्र में विशेषज्ञ बन सके।",
        "section.llms.smarter.rag.title": "ओपन बुक टेस्ट",
        "section.llms.smarter.rag.desc": "सब कुछ याद रखने के बजाय, हम एआई को एक विश्वसनीय किताब या डेटाबेस में तथ्यों को देखने देते हैं। यह इसे चीजें बनाने से रोकता है।",
        "section.agents": "प्रवेश: एआई एजेंट्स",
        "section.agents.subtitle": "मस्तिष्क को हाथ और पैर देना।",
        "section.agents.worker.title": "डिजिटल वर्कर",
        "section.agents.worker.text": "एक एआई एजेंट टूल्स के साथ एक एलएलएम है। यह वेब ब्राउज़र का उपयोग कर सकता है, ईमेल भेज सकता है, या कोड चला सकता है। यह सिर्फ बात नहीं करता; यह करता है। इसका एक लक्ष्य है, एक योजना बनाता है, और उसे निष्पादित करता है।",
        "section.agents.worker.note": "LLM = विचारक। एजेंट = कर्ता।",
        "section.agents.diff.title": "मुख्य अंतर",
        "section.agents.diff.llm.title": "LLM (स्थिर)",
        "section.agents.diff.llm.desc": "आपके प्रश्न पूछने का इंतजार कर रहा है। उसके तुरंत बाद आपको भूल जाता है।",
        "section.agents.diff.agent.title": "एजेंट (सक्रिय)",
        "section.agents.diff.agent.desc": "एक लक्ष्य की ओर काम करता है। याद रखता है कि उसने क्या किया। गलतियों से सीखता है।",
        "section.agents.comparison.title": "त्वरित तुलना",
        "section.architecture": "एजेंट के अंदर क्या है?",
        "section.architecture.subtitle": "वे हिस्से जो इसे काम करते हैं।",
        "section.architecture.text": "एक एजेंट जादू नहीं है। यह एक प्रणाली है। इसे एक मस्तिष्क (LLM), स्मृति (संदर्भ याद रखने के लिए), और उपकरण (दुनिया के साथ बातचीत करने के लिए) की आवश्यकता होती है।",
        "section.architecture.react.title": "कदम-दर-कदम सोचना (ReAct)",
        "section.architecture.react.subtitle": "तर्क और कार्य",
        "section.architecture.react.text": "इस तरह एजेंट कठिन समस्याओं को हल करते हैं। वे अनुमान नहीं लगाते हैं। वे: 1. सोचते हैं कि क्या करना है। 2. कार्य करते हैं (एक उपकरण का उपयोग करें)। 3. परिणाम का निरीक्षण करते हैं। 4. समाप्त होने तक दोहराते हैं।",
        "section.workflows": "एजेंट टीमें",
        "section.workflows.subtitle": "जब एक एजेंट पर्याप्त नहीं होता है।",
        "section.workflows.title": "कार्यप्रवाह",
        "section.workflows.text": "कभी-कभी एक काम एक एजेंट के लिए बहुत बड़ा होता है। इसलिए हम उन्हें जोड़ते हैं। एक एजेंट \"शोधकर्ता\" हो सकता है, दूसरा \"लेखक\", और दूसरा \"संपादक\"। वे एक असली टीम की तरह एक-दूसरे को काम सौंपते हैं।",
        "section.workflows.advanced.title": "उन्नत सुविधाएँ",
        "section.workflows.advanced.teamwork.title": "टीम वर्क",
        "section.workflows.advanced.teamwork.desc": "जटिल परियोजनाओं पर एक साथ काम करने वाले कई एजेंट।",
        "section.workflows.advanced.reflection.title": "आत्म-प्रतिबिंब",
        "section.workflows.advanced.reflection.desc": "एजेंट अपने काम की जांच कर रहे हैं ताकि यह सुनिश्चित हो सके कि यह अच्छा है।",
        "section.workflows.advanced.human.title": "मानव सहायता",
        "section.workflows.advanced.human.desc": "कुछ महत्वपूर्ण करने से पहले अनुमोदन के लिए मानव से पूछना।",
        "section.workflows.advanced.adapt.title": "अनुकूलनशीलता",
        "section.workflows.advanced.adapt.desc": "अगर कुछ गलत हो जाता है तो योजना बदलना।",
        "section.workflows.future.title": "काम का भविष्य",
        "section.workflows.future.text": "यह भविष्य है। डिजिटल कार्यकर्ता उबाऊ चीजों को संभाल रहे हैं, ताकि आप बड़े विचारों पर ध्यान केंद्रित कर सकें।",
        "listen": " सुनें",
    },
    gu: {
        "nav.intro": "પરિચય",
        "nav.diagram": "આકૃતિ",
        "nav.llms": "LLMs",
        "nav.agents": "એજન્ટ્સ",
        "nav.workflows": "વર્કફ્લો",
        "nav.architecture": "આર્કિટેક્ચર",
        "hero.title": "સ્વાયત્ત AI નો યુગ",
        "hero.subtitle": "સરળ ચેટબોટ્સથી લઈને બુદ્ધિશાળી એજન્ટો સુધી જે યોજના બનાવી શકે છે, તર્ક કરી શકે છે અને કાર્યો કરી શકે છે.",
        "hero.cta": "શીખવાનું શરૂ કરો",
        "section.talking_vs_doing": "વાત કરવી વિ. કરવું",
        "section.talking_vs_doing.subtitle": "કેવી રીતે AI ફક્ત ચેટિંગથી વાસ્તવમાં કામ કરવા તરફ આગળ વધી રહ્યું છે.",
        "section.intro.big_shift.title": "મોટો ફેરફાર",
        "section.intro.big_shift.text": "AI બદલાઈ રહ્યું છે. તે પહેલા ફક્ત પ્રશ્નોના જવાબ આપતું હતું. હવે, તે કાર્ય કરી શકે છે. અમે \"ચેટબોટ્સ\" થી જે વાત કરે છે, \"એજન્ટ્સ\" તરફ આગળ વધી રહ્યા છીએ જે કામ કરે છે. આનો અર્થ એ છે કે AI હવે યોજના બનાવી શકે છે, શીખી શકે છે, અને તમારા કાર્યોને પૂર્ણ કરવામાં મદદ કરી શકે છે, ફક્ત તેમના વિશે લખી શકતું નથી.",
        "section.intro.analogy.text1": "આ રીતે વિચારો: જૂનું AI એક સ્માર્ટ જ્ઞાનકોશ જેવું હતું. તે ઘણું જાણતું હતું પણ કંઈ કરી શકતું નહોતું. નવું AI (એજન્ટિક AI) એક સ્માર્ટ ઇન્ટર્ન જેવું છે. તે વસ્તુઓ જાણે છે અને તમારા માટે કામ પણ કરી શકે છે.",
        "section.intro.analogy.text2": "આ વ્યવસાયો માટે ખૂબ મોટું છે. ફક્ત જવાબો મેળવવાને બદલે, હવે તમે આખી નોકરીઓને સ્વચાલિત કરી શકો છો. આ પરિણામો મેળવવા વિશે છે, ફક્ત ટેક્સ્ટ નહીં.",
        "section.intro.future.title": "ભવિષ્યનો દૃષ્ટિકોણ",
        "section.intro.future.text": "2028 સુધીમાં, નિષ્ણાતો કહે છે કે 15% કાર્ય નિર્ણયો આ સ્વાયત્ત એજન્ટો દ્વારા લેવામાં આવશે. આ ઓટોમેશનમાં આગામી મોટું પગલું છે.",
        "section.diagram": "એજન્ટો કેવી રીતે વિચારે છે",
        "section.diagram.subtitle": "તે સરળ લૂપ જે AI ને જાતે સમસ્યાઓ ઉકેલવા દે છે.",
        "section.llms": "મગજ: LLMs",
        "section.llms.subtitle": "જાદુ પાછળની મુખ્ય તકનીકને સમજવી.",
        "section.llms.student.title": "સ્માર્ટ વિદ્યાર્થી",
        "section.llms.student.text": "એક મોટું ભાષા મોડેલ (LLM) એક વિદ્યાર્થી જેવું છે જેણે પુસ્તકાલયમાં દરેક પુસ્તક વાંચ્યું છે. તે દરેક વસ્તુ વિશે ઘણું જાણે છે—ઇતિહાસ, વિજ્ઞાન, કોડિંગ. તે આ જ્ઞાનનો ઉપયોગ આગળ શું કહેવું તે અનુમાન કરવા માટે કરે છે.",
        "section.llms.pros_cons.title": "ફાયદા અને ગેરફાયદા",
        "section.llms.pros_cons.fast.title": "સુપર ફાસ્ટ",
        "section.llms.pros_cons.fast.desc": "લખવા, સારાંશ આપવા અને તરત જ પ્રશ્નોના જવાબ આપવામાં મહાન.",
        "section.llms.pros_cons.cant_act.title": "કાર્ય કરી શકતું નથી",
        "section.llms.pros_cons.cant_act.desc": "તે એક બોક્સમાં ફસાયેલું છે. તે ઇમેઇલ લખી શકે છે, પણ તેને મોકલી શકતું નથી.",
        "section.llms.pros_cons.wrong.title": "ખોટું હોઈ શકે છે",
        "section.llms.pros_cons.wrong.desc": "ક્યારેક તે વસ્તુઓ બનાવી કાઢે છે (ભ્રમણા) જો તેને જવાબ ખબર ન હોય.",
        "section.llms.pros_cons.memory.title": "કોઈ મેમરી નથી",
        "section.llms.pros_cons.memory.desc": "ચેટ સમાપ્ત થયા પછી તે બધું ભૂલી જાય છે. તે ભૂલોથી શીખતું નથી.",
        "section.llms.smarter.title": "તેને વધુ હોશિયાર બનાવવું",
        "section.llms.smarter.finetuning.title": "વિશિષ્ટ તાલીમ",
        "section.llms.smarter.finetuning.desc": "જેમ કે ડૉક્ટરને મેડિકલ સ્કૂલમાં મોકલવા. અમે AI ને ચોક્કસ વસ્તુઓ શીખવીએ છીએ જેથી તે એક ક્ષેત્રમાં નિષ્ણાત બની શકે.",
        "section.llms.smarter.rag.title": "ઓપન બુક ટેસ્ટ",
        "section.llms.smarter.rag.desc": "બધું યાદ રાખવાને બદલે, અમે AI ને વિશ્વસનીય પુસ્તક અથવા ડેટાબેઝમાં તથ્યો જોવા દઈએ છીએ. આ તેને વસ્તુઓ બનાવવાથી રોકે છે.",
        "section.agents": "પ્રવેશ: AI એજન્ટ્સ",
        "section.agents.subtitle": "મગજને હાથ અને પગ આપવા.",
        "section.agents.worker.title": "ડિજિટલ વર્કર",
        "section.agents.worker.text": "એક AI એજન્ટ ટૂલ્સ સાથેનું LLM છે. તે વેબ બ્રાઉઝરનો ઉપયોગ કરી શકે છે, ઇમેઇલ મોકલી શકે છે, અથવા કોડ ચલાવી શકે છે. તે ફક્ત વાત કરતું નથી; તે કરે છે. તેનું એક લક્ષ્ય છે, યોજના બનાવે છે, અને તેને અમલમાં મૂકે છે.",
        "section.agents.worker.note": "LLM = વિચારક. એજન્ટ = કર્તા.",
        "section.agents.diff.title": "મુખ્ય તફાવતો",
        "section.agents.diff.llm.title": "LLM (સ્થિર)",
        "section.agents.diff.llm.desc": "તમારા પ્રશ્ન પૂછવાની રાહ જોઈ રહ્યું છે. તેના પછી તરત જ તમને ભૂલી જાય છે.",
        "section.agents.diff.agent.title": "એજન્ટ (સક્રિય)",
        "section.agents.diff.agent.desc": "એક લક્ષ્ય તરફ કામ કરે છે. યાદ રાખે છે કે તેણે શું કર્યું. ભૂલોથી શીખે છે.",
        "section.agents.comparison.title": "ઝડપી સરખામણી",
        "section.architecture": "એજન્ટની અંદર શું છે?",
        "section.architecture.subtitle": "તે ભાગો જે તેને કાર્યરત કરે છે.",
        "section.architecture.text": "એક એજન્ટ જાદુ નથી. તે એક સિસ્ટમ છે. તેને મગજ (LLM), મેમરી (સંદર્ભ યાદ રાખવા માટે), અને સાધનો (દુનિયા સાથે વાતચીત કરવા માટે) ની જરૂર છે.",
        "section.architecture.react.title": "પગલું-દર-પગલું વિચારવું (ReAct)",
        "section.architecture.react.subtitle": "તર્ક અને કાર્ય",
        "section.architecture.react.text": "આ રીતે એજન્ટો મુશ્કેલ સમસ્યાઓ ઉકેલે છે. તેઓ અનુમાન લગાવતા નથી. તેઓ: 1. વિચારે છે કે શું કરવું. 2. કાર્ય કરે છે (સાધનનો ઉપયોગ કરે છે). 3. પરિણામનું નિરીક્ષણ કરે છે. 4. સમાપ્ત થાય ત્યાં સુધી પુનરાવર્તન કરે છે.",
        "section.workflows": "એજન્ટ ટીમો",
        "section.workflows.subtitle": "જ્યારે એક એજન્ટ પૂરતો નથી.",
        "section.workflows.title": "વર્કફ્લો",
        "section.workflows.text": "ક્યારેક એક કામ એક એજન્ટ માટે ખૂબ મોટું હોય છે. તેથી અમે તેમને જોડીએ છીએ. એક એજન્ટ \"સંશોધક\" હોઈ શકે છે, બીજો \"લેખક\", અને બીજો \"સંપાદક\". તેઓ એક વાસ્તવિક ટીમની જેમ એકબીજાને કામ સોંપે છે.",
        "section.workflows.advanced.title": "અદ્યતન સુવિધાઓ",
        "section.workflows.advanced.teamwork.title": "ટીમ વર્ક",
        "section.workflows.advanced.teamwork.desc": "જટિલ પ્રોજેક્ટ્સ પર એક સાથે કામ કરતા બહુવિધ એજન્ટો.",
        "section.workflows.advanced.reflection.title": "આત્મ-પ્રતિબિંબ",
        "section.workflows.advanced.reflection.desc": "એજન્ટો તેમના પોતાના કામની તપાસ કરી રહ્યા છે જેથી ખાતરી થઈ શકે કે તે સારું છે.",
        "section.workflows.advanced.human.title": "માનવ મદદ",
        "section.workflows.advanced.human.desc": "કંઈક મહત્વપૂર્ણ કરતા પહેલા મંજૂરી માટે માનવને પૂછવું.",
        "section.workflows.advanced.adapt.title": "અનુકૂલનક્ષમતા",
        "section.workflows.advanced.adapt.desc": "જો કંઈક ખોટું થાય તો યોજના બદલવી.",
        "section.workflows.future.title": "કામનું ભવિષ્ય",
        "section.workflows.future.text": "આ ભવિષ્ય છે. ડિજિટલ કામદારો કંટાળાજનક વસ્તુઓ સંભાળી રહ્યા છે, જેથી તમે મોટા વિચારો પર ધ્યાન કેન્દ્રિત કરી શકો.",
        "listen": "સાંભળો",
    },
};

type LanguageContextType = {
    language: Language;
    setLanguage: (lang: Language) => void;
    t: (key: string) => string;
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export function LanguageProvider({ children }: { children: ReactNode }) {
    const [language, setLanguage] = useState<Language>("en");

    const t = (key: string) => {
        return translations[language][key] || key;
    };

    return (
        <LanguageContext.Provider value={{ language, setLanguage, t }}>
            {children}
        </LanguageContext.Provider>
    );
}

export function useLanguage() {
    const context = useContext(LanguageContext);
    if (context === undefined) {
        throw new Error("useLanguage must be used within a LanguageProvider");
    }
    return context;
}
